In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

- Numpy merupakan library python digunakan untuk komputasi matriks.
- Matplotlib merupakan library python digunakan untuk presentasi data berupa grafik atau plot.
- Pandas untuk import csv, txt, exel.

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

- : mengambil semua data
- :-1 mengambil semua kecuali yang terakhir

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['France' 45.0 92000.0]
 ['Spain' 30.0 60000.0]
 ['Germany' 20.0 64000.0]
 ['Spain' 28.0 51000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 68000.0]
 ['Spain' nan 22000.0]
 ['France' 58.0 67000.0]
 ['Germany' 50.0 53000.0]
 ['France' 50.0 47000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

- yang berisi nan diisi mean, bisa modus juga median
- harus difitkan disimpan pada variabel x ambil kolom 1-3
- lalu transfomkan lalu masukkan variabel x

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 39.166666666666664 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['France' 45.0 92000.0]
 ['Spain' 30.0 60000.0]
 ['Germany' 20.0 64000.0]
 ['Spain' 28.0 51000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 68000.0]
 ['Spain' 39.166666666666664 22000.0]
 ['France' 58.0 67000.0]
 ['Germany' 50.0 53000.0]
 ['France' 50.0 47000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

- onehot untuk mengubah dalam bentuk nominal jadi matriks dibantu encoder
- gunakan encoder 0

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.166666666666664 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 45.0 92000.0]
 [0.0 0.0 1.0 30.0 60000.0]
 [0.0 1.0 0.0 20.0 64000.0]
 [0.0 0.0 1.0 28.0 51000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 68000.0]
 [0.0 0.0 1.0 39.166666666666664 22000.0]
 [1.0 0.0 0.0 58.0 67000.0]
 [0.0 1.0 0.0 50.0 53000.0]
 [1.0 0.0 0.0 50.0 47000.0]]


- run sekali matriks orde 3 kalo kedua orde 4

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

- menimpa noyes menjadi 0101

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

- testing 20% training sisanya

In [12]:
print(x_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 58.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 28.0 51000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 50.0 47000.0]
 [0.0 1.0 0.0 50.0 53000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 35.0 68000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 20.0 64000.0]
 [0.0 0.0 1.0 30.0 60000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 39.166666666666664 22000.0]
 [0.0 0.0 1.0 39.166666666666664 52000.0]
 [1.0 0.0 0.0 45.0 92000.0]]


In [14]:
print(y_train)

[0 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1]


In [15]:
print(y_test)

[0 0 0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 1.0 0.0 -0.8724307635068188 -0.7990565361023025]
 [0.0 1.0 0.0 0.11058981509241365 -0.10530202413751273]
 [0.0 1.0 0.0 0.11058981509241365 -0.10530202413751273]
 [1.0 0.0 0.0 1.880026856571032 0.4893447004037356]
 [1.0 0.0 0.0 0.8970062779717997 1.6786381494862324]
 [0.0 0.0 1.0 -1.1673369370865885 -1.3937032606435509]
 [0.0 0.0 1.0 -1.0690348792266653 -1.0963798983729267]
 [1.0 0.0 0.0 0.5037980465321067 0.9848836375214426]
 [1.0 0.0 0.0 1.0936103936916461 -1.4928110480670922]
 [0.0 1.0 0.0 1.0936103936916461 -0.8981643235258439]
 [1.0 0.0 0.0 -0.18431635848735609 0.4893447004037356]
 [1.0 0.0 0.0 -0.3809204742072026 0.588452487827277]
 [0.0 1.0 0.0 1.0936103936916461 2.075069299180398]
 [0.0 1.0 0.0 -1.8554513421060512 0.19202133813311145]
 [0.0 0.0 1.0 -0.8724307635068188 -0.20440981156105412]
 [1.0 0.0 0.0 -0.3809204742072026 -0.40262538640813694]]


- mengubah skala besar

In [18]:
print(x_test)

[[0.0 0.0 1.0 -0.08601430062743284 -0.10530202413751273]
 [0.0 0.0 1.0 0.028671433542477382 -3.970505733655627]
 [0.0 0.0 1.0 0.028671433542477382 -0.9972721109493853]
 [1.0 0.0 0.0 0.6021001043920299 2.9670393859922704]]
